DROP TABLE IF EXISTS MEMBER_INFO;
--
create table MEMBER_INFO
(
	INDEX INT not null,
	USER_ID VARCHAR(255),
	USER_NAME VARCHAR(255),
	ACCOUNT_NUM VARCHAR(255),
	ACCOUNT_PW VARCHAR(255),
	IDCARD_IMG BLOB,
	IDCARD_USER_NAME VARCHAR(255),
	REGIS_NUM VARCHAR(255),
	IDCARD_NUM VARCHAR(255),
	IDCARD_REG_DAY DATE,
	primary key (INDEX)
);
--
--
-- create table SET_ACCOUNT_PROCESS
-- (
-- 	INDEX INT not null,
-- 	USER_INFO_PK VARCHAR(255),
-- 	LAST_PAGE VARCHAR(255),
-- 	FIRST_SET_CHECK VARCHAR(1),
-- 	TERMS_CHECK VARCHAR(1),
-- 	TERMS_CHECK_DATETIME DATETIME,
-- 	PW_CHECK VARCHAR(255),
-- 	PW_CHECK_DATETIME DATETIME,
-- 	IDENTI_CHECK VARCHAR(255),
-- 	IDENTI_CHECK_DATETIME DATETIME,
-- 	TRANSFER_CHECK VARCHAR(1),
-- 	TRANSFER_CHECK_DATETIME DATETIME,
-- 	primary key (INDEX)
-- );
--

-- DROP TABLE IF EXISTS MEMBER_INFO;
--
-- CREATE TABLE MEMBER_INFO (ID INT PRIMARY KEY AUTO_INCREMENT, user_name VARCHAR, COUNTRY VARCHAR, POPULATION INT);


