DROP TABLE IF EXISTS MEMBER_INFO;

create table MEMBER_INFO
(
	INDEX INT auto_increment not null,
	USER_ID VARCHAR(255),
	USER_NAME VARCHAR(255),
	ACCOUNT_NUM VARCHAR(255),
	ACCOUNT_PW VARCHAR(255),  -- 암호화하여 저장
	IDCARD_IMG VARCHAR(500),
	IDCARD_USER_NAME VARCHAR(255),
	REGIS_NUM VARCHAR(255),
	IDCARD_NUM VARCHAR(255), -- 암호화하여 저장
	IDCARD_REG_DAY DATE,
	primary key (INDEX)
);



